### ISSUE TITLE
POOR README

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/emoji-RESTful-api#10]
This is a very poor readme. How do I use your API?. Where is the documentation for all the routes that exist and the kind of information that they return and the kind of status codes.

How do i know how to be authenticated to make a post request.

All those vital info is missing.

Please fix ASAP!

**Comment by unicodeveloper** [comment]
Give examples of each api request with sample info that it returns

**Comment by unicodeveloper** [comment]
Please correct the grammatical blunder here too
<img width="1035" alt="screen shot 2015-10-26 at 6 14 51 am" src="https://cloud.githubusercontent.com/assets/2946769/10721747/fa548b42-7ba8-11e5-8be0-c01d699834a4.png">

**Comment by kola-er** [comment]
Acknowledged. I will treat it ASAP!

**Comment by unicodeveloper** [comment]
@andela-kerinoso you still haven't fixed this issue

**Comment by kola-er** [comment]
Resolved
